###########################
#   Project information   #
###########################
site_name: FLEE
# site_url: https://flee.readthedocs.io
site_description: Simulation toolkit for the movement of individuals

##################
#   Repository   #
##################
repo_name: arabnejad/flee
repo_url: https://github.com/arabnejad/flee

site_author: Hamid Arabnejad
docs_dir: docs/

# Copyright
copyright: Derek Groen, Diana Suleimenova, Hamid Arabnejad, Alireza Jahani

####################
#   Social Media   #
####################
extra:
  social:
    # - icon: fontawesome/solid/home
    #   link: https://up42.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/arabnejad/flee
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/u/up42
    - icon: fontawesome/solid/envelope
      link: mailto:djgroen@gmail.com 

#####################
#   Configuration   #
#####################
theme:
  name: material
  # 404 page
  custom_dir: docs/theme/overrides
  static_templates:
    - 404.html  
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en  
  # palette:
  #   # primary: indigo
  #   # accent: indigo
  #   primary: "blue grey"
  #   accent: "blue"    
  #   # scheme: preference
  font:    
    text: Roboto
    code: Roboto Mono
  palette:
    primary: black    
  features:
    - search.suggest
    - search.highlight    
    - navigation.tabs
    - navigation.expand  
    # - instant
    # - toc.integrate
    # - navigation.sections
  favicon: images/logo/logo.png # browser tab icon
  logo: images/empty.png
  icon:
    repo: fontawesome/brands/github

###############
#   Plugins   #
###############
plugins:
  - search
  # - enumerate-headings  
  - autolinks
  - awesome-pages:
      collapse_single_pages: true
      strict: true  
  - macros
  - mkdocstrings:
      handlers:
          python:
            setup_commands:
              - import sys
              - sys.path.append("flee")
              # - sys.path.insert(0, ".")
            rendering:
              show_root_heading: false
              show_source: true
              show_category_heading: true
            selection:
              # new_path_syntax: true
              filters:
                - "!^_"  # exlude all members starting with _
  - mermaid2:
      arguments:
        securityLevel: 'loose'
        theme: 'forest'

  # https://timvink.github.io/mkdocs-print-site-plugin/customization/pdf_button.html
  # - print-site:
  #     add_full_urls: false
  #     add_table_of_contents: true
  #     toc_title: "Table of Contents"
  #     toc_depth: 2
  #     add_full_urls: false
  #     enumerate_headings: true
  #     enumerate_figures: true
  #     add_cover_page: true
  #     add_to_navigation: false



#################
#   Extra CSS   #
#################
extra_css:
  - static/css/custom.css
  - static/css/colors.css
  # - static/css/terminal.css
  # - static/css/extra.css

################
#   Extra JS   #
################
# source https://gokumohandas.github.io/MLOps/tagifai/data/#tagifai.data
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - static/js/extra.js
  # - static/js/terminal.js

##################
#   Extensions   #
##################
markdown_extensions:
  # - admonition
  - markdown.extensions.admonition # alerts  
  # - attr_list
  - markdown.extensions.attr_list # add HTML and CSS to Markdown elements
  # - def_list  
  - markdown.extensions.def_list
  # - footnotes
  - markdown.extensions.footnotes
  # - meta  
  - markdown.extensions.meta
  # - toc:
  #     toc_depth: 4  
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
      toc_depth: 4
  - pymdownx.arithmatex: # mathjax
      generic: true      
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details #  collapsible alerts
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.escapeall:
      nbsp: true      
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: arabnejad
  #     repo: pyDAGSim
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # insert content from other files
      check_paths: true
  - pymdownx.superfences: # nest code and content inside alerts
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
          # format: !!python/name:pymdownx.superfences.fence_div_format
          format: !!python/name:mermaid2.fence_mermaid

  - pymdownx.tabbed # content tabs
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true      
  - pymdownx.tilde
  - pymdownx.tabbed
  - mkdocs-click
  - codehilite:
      guess_lang: false  
  - toc:
      permalink: true
#################
#   Page tree   #
#################
nav:
    - Home:
      - Introduction: index.md
      - Installation and Testing: Installation_and_Testing.md
      - Simulation instance construction: Simulation_instance_construction.md
      - Simulation instance execution : Simulation_instance_execution.md
    #   - Getting Started: pages/GettingStarted.md
    #   - Examples:
    #     - Add Tasks: pages/examples/add_tasks.md
    #     - Static Min-Min: pages/examples/min_min_scheduling_static.md

    - Code Reference:
       - flee:
         - Person: code_reference/flee.md
    #     - HOST: reference/base/HOST.md
    #     - CPU: reference/base/CPU.md
    #     - LINK: reference/base/LINK.md
